version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "8000:8000"


  database:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5433:5432"
#    environment:
#      - 'POSTGRES_DB:tododb'
#      - 'POSTGRES_USER:todo_user'
#      - 'POSTGRES_PASSWORD:todo_pass'

